// ui/angular/src/app/active/active.component.ts
import { Component, OnInit } from '@angular/core';

import { TodoService, TodoItem} from './../core';

@Component({
  selector: '',
  templateUrl: './active.component.html'
})
export class ActiveComponent implements OnInit {
  
  todos: TodoItem[] = [];
  filter: string = 'active'; // filter only active todo list item

  constructor(
    private todoService: TodoService
  ) {}

  ngOnInit() {
    this.todos = this.todoService.todos;
  }

 }

// ui/vue/src/views/Active.vue
<template>
  <ul class="todo-list unstyled">
    <TodoItem v-for="item in todos" v-bind:item="item" :key="item.key"></TodoItem>
  </ul>
</template>

<script>
import TodoItem from '@/components/TodoItem.vue'

export default {
  name: 'active',
  components: {
    TodoItem
  },
  computed: {
    todos () {
      // filter todos list and show only active
      return this.$store.getters.activeTodo
    }
  }
}
</script>
