// ui/reactjs/src/routes/completed.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import TodoList from './../components/todo/todo-list';

class Completed extends Component {
  render() {

    // filter todos list and show only completed
    const todos = this.props.todos.filter((item)=> {
      return item.completed;
    }).map((item)=> {
      return <TodoList key={item.key} item={item} />;
    });

    return (
      <ul className="todo-list unstyled">
        {todos}
      </ul>
    );
  }
}

const mapStateToProps = state => {
  return {
    todos: state.todos.list
  }
};

const mapDispatchToProps = dispatch => ({
  
});

export default connect(mapStateToProps, mapDispatchToProps)(Completed);

// ui/vue/src/views/Completed.vue
<template>
  <ul class="todo-list unstyled">
    <TodoItem v-for="item in todos" v-bind:item="item" :key="item.key"></TodoItem>
  </ul>
</template>

<script>
import TodoItem from '@/components/TodoItem.vue'

export default {
  name: 'active',
  components: {
    TodoItem
  },
  computed: {
    todos () {
      // filter todos list and show only completed
      return this.$store.getters.completedTodo
    }
  }
}
</script>
