// ui/reactjs/src/components/footer.js
import React, { Component } from 'react';

export default class Footer extends Component {
  render() {
    const year = new Date().getFullYear();

    return (
      <footer className="main-footer text-center">
        <span className="tip">Press Enter to submit and double click label to edit.</span>
        <div className="copyright">
          <span>{year} &copy; SWIM.ai</span>
        </div>
      </footer>
    );
  }
}

// ui/angular/src/app/shared/layout/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'layout-footer',
  templateUrl: './footer.component.html'
})
export class LayoutFooterComponent {
  year = new Date().getFullYear();

  constructor() { }
}
<footer class="main-footer text-center">
  <span class="tip">Press Enter to submit and double click label to edit.</span>
  <div class="copyright">
    <span>{{year}} &copy; SWIM.ai</span>
  </div>
</footer>
