// ui/angular/src/app/app.component.ts
import { Component, OnInit, OnDestroy} from '@angular/core';

import { TodoService } from './core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  constructor(
    private todoService: TodoService
  ) {}

  /**
    * When the app is ngOnInit we open Map downlink 
    * to Subscribe totodos list. When the data is updated
    * we will send an action SUBSCRIBE_ITEM to keep track
    * of the state of the todo list. For todo list we 
    * mainly track if new item is added or rmeove or updated
    */
  ngOnInit() {
    this.todoService.openTodoLink();
  }

  /**
    * When we ngOnDestroy is best if we close the Map downlink 
    * if we are not using.
    */
  ngOnDestroy() {
    this.todoService.closeTodoLink();
  }
}

<main class="container">
  <layout-header></layout-header>
  <section class="todo-wrap">
    <h2 class="title">Angular - Todo List</h2>
    <div class="todo-header">
      <todo-add></todo-add>

      <ul class="filter unstyled">
        <li><a [routerLink]="''" routerLinkActive="active" [routerLinkActiveOptions]="{exact:
          true}">All</a></li>
        <li><a [routerLink]="'active'" routerLinkActive="active">Active</a></li>
        <li><a [routerLink]="'completed'" routerLinkActive="active">Completed</a></li>
      </ul>  
    </div>
    
    <router-outlet></router-outlet>
  </section>

  <layout-footer></layout-footer>
</main>

// ui/vue/src/App.vue
<template>
  <div id="app">
    <main class="container">
      <app-header></app-header>
      <section class="todo-wrap">
        <h2 class="title">Vue - Todo List</h2>
        <div class="todo-header">
          <TodoInput></TodoInput>
          <ul class="filter unstyled">
            <li><router-link to="/">All</router-link></li>
            <li><router-link to="/active">Active</router-link></li>
            <li><router-link to="/completed">Completed</router-link></li>
          </ul><!-- ./filter -->

        </div><!-- ./todo-header -->

        <router-view/>
      </section><!-- ./todo-wrap -->

      <app-footer></app-footer>
    </main><!-- ./container -->
  </div>
</template>

<script>
import AppHeader from './components/AppHeader.vue'
import AppFooter from './components/AppFooter.vue'
import TodoInput from './components/TodoInput.vue'

export default {
  name: 'app',
  components: {
    AppHeader,
    AppFooter,
    TodoInput
  },
  /**
    * When the app is mount we open Map downlink 
    * to Subscribe totodos list. When the data is updated
    * we will send an action SUBSCRIBE_ITEM to keep track
    * of the state of the todo list. For todo list we 
    * mainly track if new item is added or rmeove or updated
    */
  mounted () {
    this.connect()
  },
  /**
    * When we unmount is best if we close the Map downlink 
    * if we are not using.
    */
  beforeDestroy () {
    this.disconnect()
  },
  methods: {
    connect () {
      this.$store.dispatch('openTodoLink')
    },
    disconnect () {
      this.$store.dispatch('closeTodoLink')
    }
  }
}
</script>

<style src="./app.css"></style>
