// ui/vue/src/views/Completed.vue
<template>
  <ul class="todo-list unstyled">
    <TodoItem v-for="item in todos" v-bind:item="item" :key="item.key"></TodoItem>
  </ul>
</template>

<script>
import TodoItem from '@/components/TodoItem.vue'

export default {
  name: 'active',
  components: {
    TodoItem
  },
  computed: {
    todos () {
      // filter todos list and show only completed
      return this.$store.getters.completedTodo
    }
  }
}
</script>

// ui/angular/src/app/completed/completed.component.ts
import { Component, OnInit } from '@angular/core';

import { TodoService, TodoItem} from './../core';

@Component({
  selector: 'completed',
  templateUrl: './completed.component.html'
})
export class CompletedComponent implements OnInit {
  
  todos: TodoItem[] = [];
  filter: string = 'completed'; // filter only completed todo list item

  constructor(
    private todoService: TodoService
  ) {}

  ngOnInit() {
    this.todos = this.todoService.todos;
  }

 }
<ul class="todo-list unstyled">  
  <todo-list [todos]="todos" [filter]="filter" ></todo-list>
</ul>
